export const CATEGORIES = {
    RECKLESS_DRIVING: 'RECKLESS DRIVING',
    STOP_SIGN : 'STOP SIGN',
    RED_LIGHT: 'RED LIGHT',
    SPEED: 'SPEED',
    PLATE_OBFUSCATION: 'PLATE OBFUSCATION',
    DISTRACTED_DRIVING: 'DISTRACTED DRIVING'
}
